// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: mtt/nmshl/rds/request.proto

package rds

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBillingByEnvAndIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Env       string `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
}

func (x *GetBillingByEnvAndIDRequest) Reset() {
	*x = GetBillingByEnvAndIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtt_nmshl_rds_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillingByEnvAndIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingByEnvAndIDRequest) ProtoMessage() {}

func (x *GetBillingByEnvAndIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mtt_nmshl_rds_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingByEnvAndIDRequest.ProtoReflect.Descriptor instead.
func (*GetBillingByEnvAndIDRequest) Descriptor() ([]byte, []int) {
	return file_mtt_nmshl_rds_request_proto_rawDescGZIP(), []int{0}
}

func (x *GetBillingByEnvAndIDRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetBillingByEnvAndIDRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

type GetBillingEnvRouteByAccountIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Env       *string `protobuf:"bytes,2,opt,name=env,proto3,oneof" json:"env,omitempty"`
}

func (x *GetBillingEnvRouteByAccountIDRequest) Reset() {
	*x = GetBillingEnvRouteByAccountIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtt_nmshl_rds_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillingEnvRouteByAccountIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingEnvRouteByAccountIDRequest) ProtoMessage() {}

func (x *GetBillingEnvRouteByAccountIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mtt_nmshl_rds_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingEnvRouteByAccountIDRequest.ProtoReflect.Descriptor instead.
func (*GetBillingEnvRouteByAccountIDRequest) Descriptor() ([]byte, []int) {
	return file_mtt_nmshl_rds_request_proto_rawDescGZIP(), []int{1}
}

func (x *GetBillingEnvRouteByAccountIDRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetBillingEnvRouteByAccountIDRequest) GetEnv() string {
	if x != nil && x.Env != nil {
		return *x.Env
	}
	return ""
}

type SetRouteLabelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId     uint64 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Env           string `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	BillingSource string `protobuf:"bytes,3,opt,name=billing_source,json=billingSource,proto3" json:"billing_source,omitempty"`
	RouteLabel    string `protobuf:"bytes,4,opt,name=route_label,json=routeLabel,proto3" json:"route_label,omitempty"`
}

func (x *SetRouteLabelRequest) Reset() {
	*x = SetRouteLabelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtt_nmshl_rds_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRouteLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRouteLabelRequest) ProtoMessage() {}

func (x *SetRouteLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mtt_nmshl_rds_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRouteLabelRequest.ProtoReflect.Descriptor instead.
func (*SetRouteLabelRequest) Descriptor() ([]byte, []int) {
	return file_mtt_nmshl_rds_request_proto_rawDescGZIP(), []int{2}
}

func (x *SetRouteLabelRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *SetRouteLabelRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *SetRouteLabelRequest) GetBillingSource() string {
	if x != nil {
		return x.BillingSource
	}
	return ""
}

func (x *SetRouteLabelRequest) GetRouteLabel() string {
	if x != nil {
		return x.RouteLabel
	}
	return ""
}

type GetRouteLabelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId     uint64  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	BillingSource string  `protobuf:"bytes,2,opt,name=billing_source,json=billingSource,proto3" json:"billing_source,omitempty"`
	Env           *string `protobuf:"bytes,3,opt,name=env,proto3,oneof" json:"env,omitempty"`
}

func (x *GetRouteLabelRequest) Reset() {
	*x = GetRouteLabelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtt_nmshl_rds_request_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRouteLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteLabelRequest) ProtoMessage() {}

func (x *GetRouteLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mtt_nmshl_rds_request_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteLabelRequest.ProtoReflect.Descriptor instead.
func (*GetRouteLabelRequest) Descriptor() ([]byte, []int) {
	return file_mtt_nmshl_rds_request_proto_rawDescGZIP(), []int{3}
}

func (x *GetRouteLabelRequest) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetRouteLabelRequest) GetBillingSource() string {
	if x != nil {
		return x.BillingSource
	}
	return ""
}

func (x *GetRouteLabelRequest) GetEnv() string {
	if x != nil && x.Env != nil {
		return *x.Env
	}
	return ""
}

var File_mtt_nmshl_rds_request_proto protoreflect.FileDescriptor

var file_mtt_nmshl_rds_request_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x74, 0x74, 0x2f, 0x6e, 0x6d, 0x73, 0x68, 0x6c, 0x2f, 0x72, 0x64, 0x73, 0x2f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d,
	0x74, 0x74, 0x2e, 0x6e, 0x6d, 0x73, 0x68, 0x6c, 0x2e, 0x72, 0x64, 0x73, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c,
	0x6c, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x45, 0x6e, 0x76, 0x41, 0x6e, 0x64, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02,
	0x20, 0x01, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x03, 0x65, 0x6e, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72,
	0x02, 0x10, 0x01, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x22, 0x6d, 0x0a, 0x24, 0x47, 0x65, 0x74, 0x42,
	0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x76, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x42, 0x79,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x01, 0x52, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x88, 0x01, 0x01, 0x42,
	0x06, 0x0a, 0x04, 0x5f, 0x65, 0x6e, 0x76, 0x22, 0xb3, 0x01, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x01, 0x52, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x03,
	0x65, 0x6e, 0x76, 0x12, 0x2e, 0x0a, 0x0e, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x72, 0x02, 0x10, 0x01, 0x52, 0x0d, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10,
	0x01, 0x52, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x8d, 0x01,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32,
	0x02, 0x20, 0x01, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2e,
	0x0a, 0x0e, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52,
	0x0d, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x15,
	0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x65,
	0x6e, 0x76, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x65, 0x6e, 0x76, 0x42, 0x46, 0x0a,
	0x11, 0x6d, 0x74, 0x74, 0x2e, 0x6e, 0x6d, 0x73, 0x68, 0x6c, 0x2e, 0x72, 0x64, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x2e, 0x72, 0x6e, 0x64, 0x2e, 0x6d, 0x74, 0x74, 0x2f,
	0x6d, 0x74, 0x74, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x74, 0x74, 0x2f, 0x6e, 0x6d, 0x73, 0x68, 0x6c, 0x2f, 0x72, 0x64,
	0x73, 0x3b, 0x72, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mtt_nmshl_rds_request_proto_rawDescOnce sync.Once
	file_mtt_nmshl_rds_request_proto_rawDescData = file_mtt_nmshl_rds_request_proto_rawDesc
)

func file_mtt_nmshl_rds_request_proto_rawDescGZIP() []byte {
	file_mtt_nmshl_rds_request_proto_rawDescOnce.Do(func() {
		file_mtt_nmshl_rds_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_mtt_nmshl_rds_request_proto_rawDescData)
	})
	return file_mtt_nmshl_rds_request_proto_rawDescData
}

var file_mtt_nmshl_rds_request_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mtt_nmshl_rds_request_proto_goTypes = []interface{}{
	(*GetBillingByEnvAndIDRequest)(nil),          // 0: mtt.nmshl.rds.GetBillingByEnvAndIDRequest
	(*GetBillingEnvRouteByAccountIDRequest)(nil), // 1: mtt.nmshl.rds.GetBillingEnvRouteByAccountIDRequest
	(*SetRouteLabelRequest)(nil),                 // 2: mtt.nmshl.rds.SetRouteLabelRequest
	(*GetRouteLabelRequest)(nil),                 // 3: mtt.nmshl.rds.GetRouteLabelRequest
}
var file_mtt_nmshl_rds_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mtt_nmshl_rds_request_proto_init() }
func file_mtt_nmshl_rds_request_proto_init() {
	if File_mtt_nmshl_rds_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mtt_nmshl_rds_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillingByEnvAndIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mtt_nmshl_rds_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillingEnvRouteByAccountIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mtt_nmshl_rds_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRouteLabelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mtt_nmshl_rds_request_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRouteLabelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mtt_nmshl_rds_request_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_mtt_nmshl_rds_request_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mtt_nmshl_rds_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mtt_nmshl_rds_request_proto_goTypes,
		DependencyIndexes: file_mtt_nmshl_rds_request_proto_depIdxs,
		MessageInfos:      file_mtt_nmshl_rds_request_proto_msgTypes,
	}.Build()
	File_mtt_nmshl_rds_request_proto = out.File
	file_mtt_nmshl_rds_request_proto_rawDesc = nil
	file_mtt_nmshl_rds_request_proto_goTypes = nil
	file_mtt_nmshl_rds_request_proto_depIdxs = nil
}
