// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: mtt/nmshl/rds/response.proto

package rds

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBillingByEnvAndIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Billing []string `protobuf:"bytes,1,rep,name=billing,proto3" json:"billing,omitempty"`
}

func (x *GetBillingByEnvAndIDResponse) Reset() {
	*x = GetBillingByEnvAndIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtt_nmshl_rds_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillingByEnvAndIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingByEnvAndIDResponse) ProtoMessage() {}

func (x *GetBillingByEnvAndIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mtt_nmshl_rds_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingByEnvAndIDResponse.ProtoReflect.Descriptor instead.
func (*GetBillingByEnvAndIDResponse) Descriptor() ([]byte, []int) {
	return file_mtt_nmshl_rds_response_proto_rawDescGZIP(), []int{0}
}

func (x *GetBillingByEnvAndIDResponse) GetBilling() []string {
	if x != nil {
		return x.Billing
	}
	return nil
}

type GetBillingEnvRouteByAccountIDResponseElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId     uint64  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	IAccount      string  `protobuf:"bytes,2,opt,name=i_account,json=iAccount,proto3" json:"i_account,omitempty"`
	BillingSource string  `protobuf:"bytes,3,opt,name=billing_source,json=billingSource,proto3" json:"billing_source,omitempty"`
	EnvId         string  `protobuf:"bytes,4,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	RouteLabel    *string `protobuf:"bytes,5,opt,name=route_label,json=routeLabel,proto3,oneof" json:"route_label,omitempty"`
}

func (x *GetBillingEnvRouteByAccountIDResponseElement) Reset() {
	*x = GetBillingEnvRouteByAccountIDResponseElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtt_nmshl_rds_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillingEnvRouteByAccountIDResponseElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingEnvRouteByAccountIDResponseElement) ProtoMessage() {}

func (x *GetBillingEnvRouteByAccountIDResponseElement) ProtoReflect() protoreflect.Message {
	mi := &file_mtt_nmshl_rds_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingEnvRouteByAccountIDResponseElement.ProtoReflect.Descriptor instead.
func (*GetBillingEnvRouteByAccountIDResponseElement) Descriptor() ([]byte, []int) {
	return file_mtt_nmshl_rds_response_proto_rawDescGZIP(), []int{1}
}

func (x *GetBillingEnvRouteByAccountIDResponseElement) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetBillingEnvRouteByAccountIDResponseElement) GetIAccount() string {
	if x != nil {
		return x.IAccount
	}
	return ""
}

func (x *GetBillingEnvRouteByAccountIDResponseElement) GetBillingSource() string {
	if x != nil {
		return x.BillingSource
	}
	return ""
}

func (x *GetBillingEnvRouteByAccountIDResponseElement) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *GetBillingEnvRouteByAccountIDResponseElement) GetRouteLabel() string {
	if x != nil && x.RouteLabel != nil {
		return *x.RouteLabel
	}
	return ""
}

type GetBillingEnvRouteByAccountIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BillingEnvRoute []*GetBillingEnvRouteByAccountIDResponseElement `protobuf:"bytes,1,rep,name=billing_env_route,json=billingEnvRoute,proto3" json:"billing_env_route,omitempty"`
}

func (x *GetBillingEnvRouteByAccountIDResponse) Reset() {
	*x = GetBillingEnvRouteByAccountIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtt_nmshl_rds_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillingEnvRouteByAccountIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingEnvRouteByAccountIDResponse) ProtoMessage() {}

func (x *GetBillingEnvRouteByAccountIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mtt_nmshl_rds_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingEnvRouteByAccountIDResponse.ProtoReflect.Descriptor instead.
func (*GetBillingEnvRouteByAccountIDResponse) Descriptor() ([]byte, []int) {
	return file_mtt_nmshl_rds_response_proto_rawDescGZIP(), []int{2}
}

func (x *GetBillingEnvRouteByAccountIDResponse) GetBillingEnvRoute() []*GetBillingEnvRouteByAccountIDResponseElement {
	if x != nil {
		return x.BillingEnvRoute
	}
	return nil
}

type SetRouteLabelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetRouteLabelResponse) Reset() {
	*x = SetRouteLabelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtt_nmshl_rds_response_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRouteLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRouteLabelResponse) ProtoMessage() {}

func (x *SetRouteLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mtt_nmshl_rds_response_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRouteLabelResponse.ProtoReflect.Descriptor instead.
func (*SetRouteLabelResponse) Descriptor() ([]byte, []int) {
	return file_mtt_nmshl_rds_response_proto_rawDescGZIP(), []int{3}
}

type GetRouteLabelResponseElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId  uint64  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	RouteLabel *string `protobuf:"bytes,2,opt,name=route_label,json=routeLabel,proto3,oneof" json:"route_label,omitempty"`
}

func (x *GetRouteLabelResponseElement) Reset() {
	*x = GetRouteLabelResponseElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtt_nmshl_rds_response_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRouteLabelResponseElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteLabelResponseElement) ProtoMessage() {}

func (x *GetRouteLabelResponseElement) ProtoReflect() protoreflect.Message {
	mi := &file_mtt_nmshl_rds_response_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteLabelResponseElement.ProtoReflect.Descriptor instead.
func (*GetRouteLabelResponseElement) Descriptor() ([]byte, []int) {
	return file_mtt_nmshl_rds_response_proto_rawDescGZIP(), []int{4}
}

func (x *GetRouteLabelResponseElement) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetRouteLabelResponseElement) GetRouteLabel() string {
	if x != nil && x.RouteLabel != nil {
		return *x.RouteLabel
	}
	return ""
}

type GetRouteLabelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteLabel []*GetRouteLabelResponseElement `protobuf:"bytes,1,rep,name=route_label,json=routeLabel,proto3" json:"route_label,omitempty"`
}

func (x *GetRouteLabelResponse) Reset() {
	*x = GetRouteLabelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtt_nmshl_rds_response_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRouteLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteLabelResponse) ProtoMessage() {}

func (x *GetRouteLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mtt_nmshl_rds_response_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteLabelResponse.ProtoReflect.Descriptor instead.
func (*GetRouteLabelResponse) Descriptor() ([]byte, []int) {
	return file_mtt_nmshl_rds_response_proto_rawDescGZIP(), []int{5}
}

func (x *GetRouteLabelResponse) GetRouteLabel() []*GetRouteLabelResponseElement {
	if x != nil {
		return x.RouteLabel
	}
	return nil
}

var File_mtt_nmshl_rds_response_proto protoreflect.FileDescriptor

var file_mtt_nmshl_rds_response_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x74, 0x74, 0x2f, 0x6e, 0x6d, 0x73, 0x68, 0x6c, 0x2f, 0x72, 0x64, 0x73, 0x2f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x6d, 0x74, 0x74, 0x2e, 0x6e, 0x6d, 0x73, 0x68, 0x6c, 0x2e, 0x72, 0x64, 0x73, 0x22, 0x38, 0x0a,
	0x1c, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x42, 0x79, 0x45, 0x6e, 0x76,
	0x41, 0x6e, 0x64, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x22, 0xde, 0x01, 0x0a, 0x2c, 0x47, 0x65, 0x74, 0x42,
	0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x76, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x42, 0x79,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x5f, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x69,
	0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x65,
	0x6e, 0x76, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x76,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x90, 0x01, 0x0a, 0x25, 0x47, 0x65, 0x74,
	0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x76, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x42,
	0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x67, 0x0a, 0x11, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e,
	0x76, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3b, 0x2e,
	0x6d, 0x74, 0x74, 0x2e, 0x6e, 0x6d, 0x73, 0x68, 0x6c, 0x2e, 0x72, 0x64, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x76, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0f, 0x62, 0x69, 0x6c, 0x6c,
	0x69, 0x6e, 0x67, 0x45, 0x6e, 0x76, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x23, 0x0a, 0x15, 0x53,
	0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x04,
	0x22, 0x73, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x65, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c,
	0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x74, 0x74, 0x2e, 0x6e, 0x6d, 0x73, 0x68, 0x6c, 0x2e,
	0x72, 0x64, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x42, 0x46, 0x0a, 0x11,
	0x6d, 0x74, 0x74, 0x2e, 0x6e, 0x6d, 0x73, 0x68, 0x6c, 0x2e, 0x72, 0x64, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x2e, 0x72, 0x6e, 0x64, 0x2e, 0x6d, 0x74, 0x74, 0x2f, 0x6d,
	0x74, 0x74, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6d, 0x74, 0x74, 0x2f, 0x6e, 0x6d, 0x73, 0x68, 0x6c, 0x2f, 0x72, 0x64, 0x73,
	0x3b, 0x72, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mtt_nmshl_rds_response_proto_rawDescOnce sync.Once
	file_mtt_nmshl_rds_response_proto_rawDescData = file_mtt_nmshl_rds_response_proto_rawDesc
)

func file_mtt_nmshl_rds_response_proto_rawDescGZIP() []byte {
	file_mtt_nmshl_rds_response_proto_rawDescOnce.Do(func() {
		file_mtt_nmshl_rds_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_mtt_nmshl_rds_response_proto_rawDescData)
	})
	return file_mtt_nmshl_rds_response_proto_rawDescData
}

var file_mtt_nmshl_rds_response_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_mtt_nmshl_rds_response_proto_goTypes = []interface{}{
	(*GetBillingByEnvAndIDResponse)(nil),                 // 0: mtt.nmshl.rds.GetBillingByEnvAndIDResponse
	(*GetBillingEnvRouteByAccountIDResponseElement)(nil), // 1: mtt.nmshl.rds.GetBillingEnvRouteByAccountIDResponseElement
	(*GetBillingEnvRouteByAccountIDResponse)(nil),        // 2: mtt.nmshl.rds.GetBillingEnvRouteByAccountIDResponse
	(*SetRouteLabelResponse)(nil),                        // 3: mtt.nmshl.rds.SetRouteLabelResponse
	(*GetRouteLabelResponseElement)(nil),                 // 4: mtt.nmshl.rds.GetRouteLabelResponseElement
	(*GetRouteLabelResponse)(nil),                        // 5: mtt.nmshl.rds.GetRouteLabelResponse
}
var file_mtt_nmshl_rds_response_proto_depIdxs = []int32{
	1, // 0: mtt.nmshl.rds.GetBillingEnvRouteByAccountIDResponse.billing_env_route:type_name -> mtt.nmshl.rds.GetBillingEnvRouteByAccountIDResponseElement
	4, // 1: mtt.nmshl.rds.GetRouteLabelResponse.route_label:type_name -> mtt.nmshl.rds.GetRouteLabelResponseElement
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mtt_nmshl_rds_response_proto_init() }
func file_mtt_nmshl_rds_response_proto_init() {
	if File_mtt_nmshl_rds_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mtt_nmshl_rds_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillingByEnvAndIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mtt_nmshl_rds_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillingEnvRouteByAccountIDResponseElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mtt_nmshl_rds_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillingEnvRouteByAccountIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mtt_nmshl_rds_response_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRouteLabelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mtt_nmshl_rds_response_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRouteLabelResponseElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mtt_nmshl_rds_response_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRouteLabelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mtt_nmshl_rds_response_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_mtt_nmshl_rds_response_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mtt_nmshl_rds_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mtt_nmshl_rds_response_proto_goTypes,
		DependencyIndexes: file_mtt_nmshl_rds_response_proto_depIdxs,
		MessageInfos:      file_mtt_nmshl_rds_response_proto_msgTypes,
	}.Build()
	File_mtt_nmshl_rds_response_proto = out.File
	file_mtt_nmshl_rds_response_proto_rawDesc = nil
	file_mtt_nmshl_rds_response_proto_goTypes = nil
	file_mtt_nmshl_rds_response_proto_depIdxs = nil
}
