// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: mtt/apistatus/request.proto

package apistatus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for method GetAPIVersion to get API version
type APIVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *APIVersionRequest) Reset() {
	*x = APIVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtt_apistatus_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIVersionRequest) ProtoMessage() {}

func (x *APIVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mtt_apistatus_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIVersionRequest.ProtoReflect.Descriptor instead.
func (*APIVersionRequest) Descriptor() ([]byte, []int) {
	return file_mtt_apistatus_request_proto_rawDescGZIP(), []int{0}
}

// Request for method GetAPIVersion to get API version
type InfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtt_apistatus_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mtt_apistatus_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_mtt_apistatus_request_proto_rawDescGZIP(), []int{1}
}

var File_mtt_apistatus_request_proto protoreflect.FileDescriptor

var file_mtt_apistatus_request_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x74, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d,
	0x74, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x13, 0x0a, 0x11,
	0x41, 0x50, 0x49, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x42, 0x4c, 0x0a, 0x11, 0x6d, 0x74, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x2e, 0x72, 0x6e, 0x64, 0x2e, 0x6d,
	0x74, 0x74, 0x2f, 0x6d, 0x74, 0x74, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x74, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x3b, 0x61, 0x70, 0x69, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mtt_apistatus_request_proto_rawDescOnce sync.Once
	file_mtt_apistatus_request_proto_rawDescData = file_mtt_apistatus_request_proto_rawDesc
)

func file_mtt_apistatus_request_proto_rawDescGZIP() []byte {
	file_mtt_apistatus_request_proto_rawDescOnce.Do(func() {
		file_mtt_apistatus_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_mtt_apistatus_request_proto_rawDescData)
	})
	return file_mtt_apistatus_request_proto_rawDescData
}

var file_mtt_apistatus_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mtt_apistatus_request_proto_goTypes = []interface{}{
	(*APIVersionRequest)(nil), // 0: mtt.apistatus.APIVersionRequest
	(*InfoRequest)(nil),       // 1: mtt.apistatus.InfoRequest
}
var file_mtt_apistatus_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mtt_apistatus_request_proto_init() }
func file_mtt_apistatus_request_proto_init() {
	if File_mtt_apistatus_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mtt_apistatus_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mtt_apistatus_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mtt_apistatus_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mtt_apistatus_request_proto_goTypes,
		DependencyIndexes: file_mtt_apistatus_request_proto_depIdxs,
		MessageInfos:      file_mtt_apistatus_request_proto_msgTypes,
	}.Build()
	File_mtt_apistatus_request_proto = out.File
	file_mtt_apistatus_request_proto_rawDesc = nil
	file_mtt_apistatus_request_proto_goTypes = nil
	file_mtt_apistatus_request_proto_depIdxs = nil
}
